/* Generated by scripts/build-cards.js from api/_catalog.js — do not edit by hand. */
window.MC_CATALOG = {
 "root": "/",
 "bundle": {
  "size": 10,
  "discount": 1000
 },
 "shipping": {
  "amount": 900,
  "label": "US shipping"
 },
 "cards": {
  "poetry-of-solace": {
   "title": "Poetry of Solace",
   "kind": "limited",
   "price": 2300,
   "was": null,
   "img": "image/cards/poetry-of-solace-front.webp",
   "url": "shop/poetry-of-solace.html"
  },
  "adonis": {
   "title": "Adonis",
   "kind": "limited",
   "price": 2300,
   "was": null,
   "img": "image/cards/adonis-front.webp",
   "url": "shop/adonis.html"
  },
  "vanity": {
   "title": "Vanity",
   "kind": "limited",
   "price": 2300,
   "was": null,
   "img": "image/cards/vanity-front.webp",
   "url": "shop/vanity.html"
  },
  "the-king": {
   "title": "The King",
   "kind": "limited",
   "price": 2300,
   "was": null,
   "img": "image/cards/the-king-front.webp",
   "url": "shop/the-king.html"
  },
  "pride": {
   "title": "Pride",
   "kind": "limited",
   "price": 2300,
   "was": null,
   "img": "image/cards/pride-front.webp",
   "url": "shop/pride.html"
  },
  "lush": {
   "title": "Lush",
   "kind": "limited",
   "price": 2300,
   "was": null,
   "img": "image/cards/lush-front.webp",
   "url": "shop/lush.html"
  },
  "businessman": {
   "title": "Businessman",
   "kind": "limited",
   "price": 2300,
   "was": null,
   "img": "image/cards/businessman-front.webp",
   "url": "shop/businessman.html"
  },
  "best-friend": {
   "title": "Best Friend",
   "kind": "limited",
   "price": 2300,
   "was": null,
   "img": "image/cards/best-friend-front.webp",
   "url": "shop/best-friend.html"
  },
  "permission": {
   "title": "Permission",
   "kind": "limited",
   "price": 2300,
   "was": null,
   "img": "image/cards/permission-front.webp",
   "url": "shop/permission.html"
  },
  "affordable-housing": {
   "title": "Affordable Housing",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/affordable-housing-front.webp",
   "url": "shop/affordable-housing.html"
  },
  "cornerstones": {
   "title": "Cornerstones",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/cornerstones-front.webp",
   "url": "shop/cornerstones.html"
  },
  "gentrification": {
   "title": "Gentrification",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/gentrification-front.webp",
   "url": "shop/gentrification.html"
  },
  "grecia-monroc": {
   "title": "Grecia Monroc",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/grecia-monroc-front.webp",
   "url": "shop/grecia-monroc.html"
  },
  "ronin": {
   "title": "Ronin",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/ronin-front.webp",
   "url": "shop/ronin.html"
  },
  "supernova": {
   "title": "Supernova",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/supernova-front.webp",
   "url": "shop/supernova.html"
  },
  "reach": {
   "title": "Reach",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/reach-front.webp",
   "url": "shop/reach.html"
  },
  "little-wanderer": {
   "title": "Little Wanderer",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/little-wanderer-front.webp",
   "url": "shop/little-wanderer.html"
  },
  "portal": {
   "title": "Portal",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/portal-front.webp",
   "url": "shop/portal.html"
  },
  "summer-field": {
   "title": "Summer Field",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/summer-field-front.webp",
   "url": "shop/summer-field.html"
  },
  "eye-of-the-storm": {
   "title": "Eye of the Storm",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/eye-of-the-storm-front.webp",
   "url": "shop/eye-of-the-storm.html"
  },
  "hidden-grove": {
   "title": "Hidden Grove",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/hidden-grove-front.webp",
   "url": "shop/hidden-grove.html"
  },
  "moonsail": {
   "title": "Moonsail",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/moonsail-front.webp",
   "url": "shop/moonsail.html"
  },
  "tidewatcher": {
   "title": "Tidewatcher",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/tidewatcher-front.webp",
   "url": "shop/tidewatcher.html"
  },
  "awakening": {
   "title": "Awakening",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/awakening-front.webp",
   "url": "shop/awakening.html"
  },
  "gilded-cage": {
   "title": "Gilded Cage",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/gilded-cage-front.webp",
   "url": "shop/gilded-cage.html"
  },
  "le-verbeux": {
   "title": "Le Verbeux",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/le-verbeux-front.webp",
   "url": "shop/le-verbeux.html"
  }
 }
}
