/* Generated by scripts/build-cards.js from api/_catalog.js — do not edit by hand. */
window.MC_CATALOG = {
 "root": "/",
 "bundle": {
  "size": 10,
  "discount": 1000,
  "price": 5000
 },
 "shipping": {
  "amount": 900,
  "label": "US shipping",
  "freeLabel": "Free US shipping"
 },
 "cards": {
  "poetry-of-solace": {
   "title": "Poetry of Solace",
   "kind": "limited",
   "price": 2300,
   "was": null,
   "img": "image/cards/poetry-of-solace-front.webp",
   "url": "shop/poetry-of-solace.html",
   "wide": true
  },
  "adonis": {
   "title": "Adonis",
   "kind": "limited",
   "price": 2300,
   "was": null,
   "img": "image/cards/adonis-front.webp",
   "url": "shop/adonis.html",
   "wide": true
  },
  "vanity": {
   "title": "Vanity",
   "kind": "limited",
   "price": 2300,
   "was": null,
   "img": "image/cards/vanity-front.webp",
   "url": "shop/vanity.html",
   "wide": false
  },
  "the-king": {
   "title": "The King",
   "kind": "limited",
   "price": 2300,
   "was": null,
   "img": "image/cards/the-king-front.webp",
   "url": "shop/the-king.html",
   "wide": false
  },
  "pride": {
   "title": "Pride",
   "kind": "limited",
   "price": 2300,
   "was": null,
   "img": "image/cards/pride-front.webp",
   "url": "shop/pride.html",
   "wide": false
  },
  "lush": {
   "title": "Lush",
   "kind": "limited",
   "price": 2300,
   "was": null,
   "img": "image/cards/lush-front.webp",
   "url": "shop/lush.html",
   "wide": false
  },
  "businessman": {
   "title": "Businessman",
   "kind": "limited",
   "price": 2300,
   "was": null,
   "img": "image/cards/businessman-front.webp",
   "url": "shop/businessman.html",
   "wide": false
  },
  "best-friend": {
   "title": "Best Friend",
   "kind": "limited",
   "price": 2300,
   "was": null,
   "img": "image/cards/best-friend-front.webp",
   "url": "shop/best-friend.html",
   "wide": false
  },
  "permission": {
   "title": "Permission",
   "kind": "limited",
   "price": 2300,
   "was": null,
   "img": "image/cards/permission-front.webp",
   "url": "shop/permission.html",
   "wide": true
  },
  "affordable-housing": {
   "title": "Affordable Housing",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/affordable-housing-front.webp",
   "url": "shop/affordable-housing.html",
   "wide": true
  },
  "cornerstones": {
   "title": "Cornerstones",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/cornerstones-front.webp",
   "url": "shop/cornerstones.html",
   "wide": true
  },
  "gentrification": {
   "title": "Gentrification",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/gentrification-front.webp",
   "url": "shop/gentrification.html",
   "wide": true
  },
  "grecia-monroc": {
   "title": "Grecia Monroc",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/grecia-monroc-front.webp",
   "url": "shop/grecia-monroc.html",
   "wide": false
  },
  "ronin": {
   "title": "Ronin",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/ronin-front.webp",
   "url": "shop/ronin.html",
   "wide": false
  },
  "supernova": {
   "title": "Supernova",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/supernova-front.webp",
   "url": "shop/supernova.html",
   "wide": false
  },
  "reach": {
   "title": "Reach",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/reach-front.webp",
   "url": "shop/reach.html",
   "wide": false
  },
  "little-wanderer": {
   "title": "Little Wanderer",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/little-wanderer-front.webp",
   "url": "shop/little-wanderer.html",
   "wide": true
  },
  "summer-field": {
   "title": "Summer Field",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/summer-field-front.webp",
   "url": "shop/summer-field.html",
   "wide": true
  },
  "hidden-grove": {
   "title": "Hidden Grove",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/hidden-grove-front.webp",
   "url": "shop/hidden-grove.html",
   "wide": false
  },
  "moonsail": {
   "title": "Moonsail",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/moonsail-front.webp",
   "url": "shop/moonsail.html",
   "wide": false
  },
  "tidewatcher": {
   "title": "Tidewatcher",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/tidewatcher-front.webp",
   "url": "shop/tidewatcher.html",
   "wide": false
  },
  "awakening": {
   "title": "Awakening",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/awakening-front.webp",
   "url": "shop/awakening.html",
   "wide": false
  },
  "gilded-cage": {
   "title": "Gilded Cage",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/gilded-cage-front.webp",
   "url": "shop/gilded-cage.html",
   "wide": false
  },
  "le-verbeux": {
   "title": "Le Verbeux",
   "kind": "open",
   "price": 600,
   "was": 1500,
   "img": "image/cards/le-verbeux-front.webp",
   "url": "shop/le-verbeux.html",
   "wide": false
  },
  "acrylic-case": {
   "title": "Magnetic Acrylic Case",
   "kind": "addon",
   "price": 400,
   "was": null,
   "note": "Magnetically sealed, one per unlimited card",
   "upsell": "Upgrade a card from its plastic slip to a magnetically sealed acrylic case",
   "short": "Acrylic case"
  },
  "acrylic-stand": {
   "title": "Acrylic Stand",
   "kind": "addon",
   "price": 100,
   "was": null,
   "note": "Display stand, one per unlimited card",
   "upsell": "Stand a card up on your shelf with an acrylic display stand",
   "short": "Acrylic stand"
  }
 },
 "addons": [
  "acrylic-case",
  "acrylic-stand"
 ]
}
